# Generated by Django 5.0.2 on 2025-12-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_rating_options_alter_rating_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
