# Generated by Django 5.0.2 on 2025-12-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_delete_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("geojson", models.JSONField()),
            ],
            options={
                "verbose_name_plural": "Areas",
            },
        ),
    ]
